### ISSUE TITLE
Static function AbstractResponse::parse() should not be abstract

### ISSUE THREAD

**Issue by artissant** [FireText/FireText-PHP-SDK#1]
Hiya,

I'm hitting this error when parsing the response from FireText API:

> Static function FireText\Api\Response\AbstractResponse::parse() should not be abstract

I'm running PHP 5.6.13. I temporarily "fixed" it by changing:

```
abstract public static function parse(Parser\ParserInterface $parser, $responseResource);
```

to:

```
public static function parse(Parser\ParserInterface $parser, $responseResource) {}
```

I appreciate it goes against the point of making it an abstract function, but was the only way I could get the error to go away! :)

**Comment by artissant** [comment]
Was having a closer look at this: you could just remove the "abstract public static function parse" line from the AbstractResponse class, as it's already defined as required in the ResponseInterface which AbstractResponse implements

**Comment by dp-firetext** [comment]
Thanks for the details artissant, we'll take a look.

**Comment by Asmblr** [comment]
We actually came to the same conclusion internally :), and the fix will be included in the next release. Fyi. PHP 7 will be removing the notice as per https://wiki.php.net/rfc/reclassify_e_strict
